spring:
  datasource:
    url: jdbc:h2:file:./BooksDB;FILE_LOCK=FS;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;
    driver-class-name: org.h2.Driver
    platform: h2
    initialize: true
    
  jpa:
    hibernate:
      ddl-auto: false
    
    
#  h2:
#    console:
#      path: /console
#      enabled: true
#      settings:
#        trace: false
#        web-allow-others: true
server:
  port: 8080
